// Re-export all OMS wire types from contracts (single source of truth)
export type {
  Order,
  OrderLineItem,
  OrderStatus,
  OrderWorkflowInput,
  OrderState,
  OrderAssignment,
  FulfillerOrderStatus,
  FulfillmentStatusUpdate,
  FulfillerOrder,
  FulfillerOrderHistoryEntry,
  FulfillerOrderItem,
  CustomerFeedback,
  StatusHistoryEntry,
  RefundLineInput,
  RefundRecord,
  ReturnRequestRecord,
  UpdateStatusSignal,
  SubmitFeedbackSignal,
  CancelOrderSignal,
  RefundOrderSignal,
  RequestReturnSignal,
  ConfirmReturnSignal,
  DenyReturnSignal,
  StatusHistoryRow,
  OrderStateName,
  OrderCommand,
} from '../contracts/oms';
